---
- name: Cloudkit hosted cluster post-install configuration
  hosts: localhost
  connection: local
  gather_facts: false

  # environment:
  #   KUBECONFIG: "{{ admin_kubeconfig | to_yaml | cloudkit.service.to_temp_file }}"

  pre_tasks:
    - name: Set template id
      ansible.builtin.set_fact:
        template_id: "trewest.ai_cluster_demo.ocp_4_17_small_ai_ready"

  tasks:
    - name: Post-install hosted cluster configuration
      ansible.builtin.include_role:
        name: "{{ template_id }}"
        tasks_from: "post_install"
