---
# ESI-specific cleanup: destroy floating IPs

- name: Destroy floating ips
  ansible.builtin.include_role:
    name: massopencloud.esi.floating_ip
    tasks_from: destroy_floating_ip.yaml
  vars:
    floating_ip_name: "{{ item }}"
  loop:
    - "{{ external_access_name }}-api"
    - "{{ external_access_name }}-ingress"
