---
- name: "Delete DNS record via PowerDNS - {{ dns_record_name }}"
  dns.powerdns.record:
    state: absent
    zone: "{{ dns_zone }}"
    record: "{{ dns_record_name }}"
    type: "{{ dns_record_type }}"
    server_url: "{{ lookup('env', 'POWERDNS_API_URL') | trim }}"
    server_id: "{{ dns_powerdns_server_id }}"
    api_key: "{{ lookup('env', 'POWERDNS_API_KEY') | trim }}"
    validate_certs: "{{ dns_powerdns_validate_certs }}"
  no_log: true
