---
dns_record_type: A
dns_record_ttl: 1800
dns_record_overwrite: true
dns_powerdns_server_id: localhost
dns_powerdns_validate_certs: "{{ lookup('env', 'POWERDNS_VALIDATE_CERTS') | default(true, true) | bool }}"
